#!/bin/bash
RED='\033[0;31m'
GREEN='\033[0;32m'
FAIL=false
echo "checking terraform formatting"
for D in $(find ./aws -mindepth 1 -maxdepth 1 -type d); do
    pushd $D 
        if $(terraform fmt); then
            echo "${GREEN}Formatting Check Passed"
        else
            printf "${RED}Formatting Check for $D Failed"
            FAIL=true
        fi
        echo ${GREEN}
    popd
done
if [ "$FAIL" = true ] ; then
    exit 1
else
    exit 0
fi