name: "setup-terraform"

on:
  workflow_call:
  
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

    - name: Set environment variables
      uses: ./.github/actions/setvars
      with:
        envVarFile: ./.env

    - name: Setup Terraform tools
      uses: cds-snc/terraform-tools-setup@v1
      env: # In case you want to override default versions
          CONFTEST_VERSION: 0.30.0 
          TERRAFORM_VERSION: 1.6.2
          TERRAGRUNT_VERSION: 0.44.4
          TF_SUMMARIZE_VERSION: 0.2.3                    

    - name: Configure credentials to Notify account using OIDC
      uses: aws-actions/configure-aws-credentials@5fd3084fc36e372ff1fff382a39b10d03659f355 # v2.2.0
      with:
        role-to-assume: arn:aws:iam::239043911459:role/notification-terraform-plan
        role-session-name: NotifyTerraformPlan
        aws-region: "ca-central-1"