apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::800095993820:role/eks-worker-role
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::800095993820:role/AWSReservedSSO_AWSAdministratorAccess_e6e62a284c3c35fc
      username: AWSAdministratorAccess:{{SessionName}}
    - rolearn: arn:aws:iam::800095993820:role/notification-admin-apply
      username: notification-admin-apply
      groups:
        - system:masters
    - rolearn: arn:aws:iam::800095993820:role/notification-api-apply
      username: notification-api-apply
      groups:
        - system:masters
    - rolearn: arn:aws:iam::800095993820:role/notification-document-download-api-apply
      username: notification-document-download-api-apply
      groups:
        - system:masters
    - rolearn: arn:aws:iam::800095993820:role/notification-documentation-apply
      username: notification-documentation-apply
      groups:
        - system:masters
    - rolearn: arn:aws:iam::800095993820:role/notification-manifests-apply
      username: notification-manifests-apply
      groups:
        - system:masters
    - rolearn: arn:aws:iam::800095993820:role/ipv4-geolocate-webservice-apply
      username: ipv4-geolocate-webservice-apply
      groups:
        - system:masters
