# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.66"
    }
    tls = {
      source  = "hashicorp/tls"
      version = "~> 4.0"
    }
    newrelic = {
      source  = "newrelic/newrelic"
      version = "~> 3.3"
    }
  }
}

provider "aws" {
  region              = "ca-central-1"
  allowed_account_ids = [239043911459]
}

provider "aws" {
  alias               = "us-west-2"
  region              = "us-west-2"
  allowed_account_ids = [239043911459]
}

provider "aws" {
  alias               = "us-east-1"
  region              = "us-east-1"
  allowed_account_ids = [239043911459]
}

# For whatever reason, Dev uses the DNS from the Staging account and 
# Production uses the DNS from the Production account, but also has a 
# different name :/  So we need to handle that here with if Logic



provider "aws" {
  alias  = "dns"
  region = "ca-central-1"
}

provider "aws" {
  alias  = "staging"
  region = "ca-central-1"
  assume_role {
    role_arn = "arn:aws:iam::239043911459:role/staging_dns_manager_role"
  }
}



