name: AI Code Review

on:
  pull_request:
    types:
      - opened
      - synchronize
permissions: write-all

jobs:
  ai_code_review:
    runs-on: ubuntu-latest
    defaults:
        run:
            working-directory: ./aws/common/variables.tf
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: AI Code Review Action
      uses: freeedcom/ai-codereviewer@8dff11715837750379472ead710753262e2ca65f # 2.7.0
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
