name: "Merge to main (Staging)"

on:
  push:
    branches:
      - main
    paths:
      - "aws/**"
      - "env/staging/**"

defaults:
  run:
    shell: bash

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.STAGING_AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.STAGING_AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ca-central-1
  TERRAFORM_VERSION: 0.13.5
  TERRAGRUNT_VERSION: v0.26.0
  TF_VAR_rds_cluster_password: ${{ secrets.STAGING_RDS_CLUSTER_PASSWORD }}
  TF_VAR_cloudwatch_slack_webhook: ${{ secrets.STAGING_CLOUDWATCH_SLACK_WEBHOOK }}

jobs:
  terraform-apply:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Fetches entire history, so we can analyze commits since last tag
          fetch-depth: 0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1.2.1
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
          terraform_wrapper: false

      - name: Setup Terragrunt
        run: |
          mkdir bin
          wget -O bin/terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/$TERRAGRUNT_VERSION/terragrunt_linux_amd64
          chmod +x bin/terragrunt
          echo "bin" >> $GITHUB_PATH

      - name: Get changed files
        id: changed-files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'json'

      - name: Get touched Terragrunt modules
        run: |
          MODULES=`echo '${{ steps.changed-files.outputs.added_modified }}' | jq -c '[.[] | match("(.*aws?)\/(.*)\/").captures[1].string] | unique | select(length > 0)'`
          echo "MODULES=$MODULES" >> $GITHUB_ENV

      - name: Get touched Terragrunt configurations
        run: |
          CONFIGS=`echo '${{ steps.changed-files.outputs.added_modified }}' | jq -c '[.[] | match("(.*env?)\/(.*staging?)\/(.*)\/").captures[2].string] | unique | select(length > 0)'`
          echo "CONFIGS=$CONFIGS" >> $GITHUB_ENV

      - name: Apply aws/common
        if: contains(env.MODULES, 'common') || contains(env.CONFIGS, 'common')
        run: |
          echo $MODULES
          cd env/staging/common
          ../../../bin/terragrunt apply --terragrunt-non-interactive -auto-approve

      - name: Apply aws/dns
        if: contains(env.MODULES, 'dns') || contains(env.CONFIGS, 'dns') 
        run: |
          echo $MODULES
          cd env/staging/dns
          ../../../bin/terragrunt apply --terragrunt-non-interactive -auto-approve

      - name: Apply aws/eks
        if: contains(env.MODULES, 'eks')  || contains(env.CONFIGS, 'eks')
        run: |
          echo $MODULES
          cd env/staging/eks
          ../../../bin/terragrunt apply --terragrunt-non-interactive -auto-approve

      - name: Apply aws/rds
        if: contains(env.MODULES, 'rds')  || contains(env.CONFIGS, 'rds')
        run: |
          echo $MODULES
          cd env/staging/rds
          ../../../bin/terragrunt apply --terragrunt-non-interactive -auto-approve

      - name: Bump version and push tag
        uses: mathieudutour/github-tag-action@v4.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: main
