name: "Edited alarms on pull requests"

on:
  pull_request:
    types: [review_requested]
    paths:
      - "**alarms.tf"

defaults:
  run:
    shell: bash

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
      - name: 'Comment PR'
        uses: actions/github-script@47f7cf65b5ced0830a325f705cad64f2f58dddf7 # v3.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { issue: { number: issue_number }, repo: { owner, repo }  } = context;

            const body = 'Updating alarms :alarm_clock:? Great! Please update the [Google Sheet](https://docs.google.com/spreadsheets/d/1gkrL3Trxw0xEkX724C1bwpfeRsTlK2X60wtCjF6MFRA/edit) and add a :thumbsup: to this message after :pray:';

            github.issues.createComment({ issue_number, owner, repo, body });
