name: "Edited alarms on pull requests"

on:
  pull_request:
    types: [review_requested]
    paths:
      - "**alarms.tf"

defaults:
  run:
    shell: bash

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
      - name: 'Comment PR'
        uses: actions/github-script@v3.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { issue: { number: issue_number }, repo: { owner, repo }  } = context;

            const body = 'Updating alarms? Great! Please update the [Google Sheet](https://docs.google.com/spreadsheets/d/1gkrL3Trxw0xEkX724C1bwpfeRsTlK2X60wtCjF6MFRA/edit) and add a :thumbsup: to this message :pray:';

            github.issues.createComment({ issue_number, owner, repo, body });
