name: "Pull requests"

on:
  pull_request:
    paths:
      - "/aws/*"
      - ".github/workflows/*"

defaults:
  run:
    shell: bash

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.STAGING_AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.STAGING_AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ca-central-1
  TERRAFORM_VERSION: 0.13.4
  TERRAGRUNT_VERSION: v0.26.0

jobs:
  terraform-plan:
    if: github.ref != 'refs/heads/master'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Setup Terragrunt
        run: |
          mkdir bin
          wget -O bin/terragrunt_linux_amd64 https://github.com/gruntwork-io/terragrunt/releases/download/$TERRAGRUNT_VERSION/terragrunt_linux_amd64
          echo "/bin" >> $GITHUB_PATH

      - name: Test Terragrunt
        run: |
          terragrunt -version

