name: Sanitize staging SMS usage data
on:
  workflow_dispatch:
  schedule:
    - cron: "0 22 * * *"

env:
  INPUT_BUCKET_1: notification-canada-ca-staging-sms-usage-logs
  INPUT_BUCKET_2: notification-canada-ca-staging-sms-usage-west-2-logs
  ACCOUNT_ID: ${{ secrets.STAGING_AWS_ACCOUNT_ID }}
  AWS_DEFAULT_REGION: ca-central-1

permissions:
  id-token: write # This is required for requesting the OIDC JWT
  contents: write # This is required for actions/checkout
  pull-requests: write

jobs:
  sanitize-sms-usage:
    runs-on: ubuntu-latest
    steps:

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Checkout
      uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

    - name: Install python packages
      run: pip install -r ./scripts/sanitize_sms_usage_logs/requirements.txt

    - name: Configure credentials to Notify using OIDC
      uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4.3.1
      with:
        role-to-assume: arn:aws:iam::${{env.ACCOUNT_ID}}:role/notification-terraform-sanitize-staging-sms-usage
        role-session-name: SanitizeStagingSMSUsage
        aws-region: ${{ env.AWS_DEFAULT_REGION }}

    - name: run script
      run: |
        python ./scripts/sanitize_sms_usage_logs/sanitize_sms_usage_logs.py ${INPUT_BUCKET_1} ${INPUT_BUCKET_1}-san --push
        python ./scripts/sanitize_sms_usage_logs/sanitize_sms_usage_logs.py ${INPUT_BUCKET_2} ${INPUT_BUCKET_2}-san --push

    - name: Notify Slack channel if this job failed
      if: ${{ failure() }}
      run: |
        json='{"text":"<!here> Sanitize staging SMS usage data failed in <https://github.com/cds-snc/notification-terraform/|notification-terraform> !"}'
        curl -X POST -H 'Content-type: application/json' --data "$json"  ${{ secrets.NOTIFY_DEV_SLACK_WEBHOOK }}
