name: "Terragrunt Format STAGING"

on:
  workflow_dispatch: 
  pull_request:
    paths:
      - ".env"
      - "aws/**"
      - "env/staging/**"
      - "env/terragrunt.hcl"
      - ".github/workflows/terragrunt_fmt_staging.yml"
env:
    tf_version: 'latest'
    tg_version: 'latest'
    tf_working_dir: './env'
permissions:
  id-token: write   # This is required for requesting the OIDC JWT
  contents: write    # This is required for actions/checkout     
  pull-requests: write

jobs:
  terragrunt:
    name: 'Terragrunt'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Terragrunt Format'
        uses: the-commons-project/terragrunt-github-actions@master
        with:
          tf_actions_version: ${{ env.tf_version }}
          tg_actions_version: ${{ env.tg_version }}
          tf_actions_binary: 'terraform'
          tf_actions_subcommand: 'fmt'
          tf_actions_working_dir: ${{ env.tf_working_dir }}
          tf_actions_comment: true
          tf_actions_fmt_write: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}