name: "Terraform security scan"

on:
  pull_request:
    paths:
      - "aws/**"
      - "env/staging/**"

defaults:
  run:
    shell: bash

jobs:
  terraform-security-scan:
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Terraform security scan
        uses: triat/terraform-security-scan@v1.2.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}