name: "Terraform security scan"

on: [pull_request]

defaults:
  run:
    shell: bash

jobs:
  terraform-security-scan:
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Terraform security scan
        uses: triat/terraform-security-scan@v2.2.1
        with:
          tfsec_version: 'v1.26.3'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
