name: "Terraform security scan"

on:
  push:
    branches:
      - main
    paths:
      - "aws/**"
      - ".github/workflows/terraform_security_scan.yml"      
  pull_request:
    paths:
      - "aws/**"
      - ".github/workflows/terraform_security_scan.yml"

jobs:
  terraform-security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkov security scan
        uses: bridgecrewio/checkov-action@f621ecfe2d83b0e2028c7e93f082812eb56d3743 # latest as of Sept 9, 2021
        with:
          directory: aws
          framework: terraform
          output_format: cli
          soft_fail: false