name: "Terraform security scan"

on: [pull_request]

defaults:
  run:
    shell: bash

jobs:
  terraform-security-scan:
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Terraform security scan
        uses: aquasecurity/tfsec-action@141b4983d1a2ada087fa804bc40e59e9cc138bcf # v1.0.2
        with:
          version: 'v0.39.26'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
