name: "Terragrunt Format and Validate - Staging"

env:
  ENVIRONMENT: staging
  ACCOUNT_ID: ${{ secrets.STAGING_AWS_ACCOUNT_ID }}
  AWS_REGION: ca-central-1
  OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN_STAGING }}
  WORKFLOW: true

on:
  workflow_dispatch:
  pull_request:
    paths:
      - ".env"
      - "aws/**"
      - "env/$ENVIRONMENT/**"
      - "env/terragrunt.hcl"
      - "env/*.tfvars"
      - ".github/workflows/terragrunt_plan_$ENVIRONMENT.yml"

permissions:
  id-token: write # This is required for requesting the OIDC JWT
  contents: write # This is required for actions/checkout
  pull-requests: write

jobs:
  terragrunt-format:
    name: Terragrunt Fmt & Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      - name: Free Disk Space
        run: |
          echo "Disk space before cleanup:"
          df -h
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/share/boost
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          echo "Disk space after cleanup:"
          df -h

      - name: Setup Terraform
        uses: ./.github/actions/setup-terraform
        with:
          role_to_assume: arn:aws:iam::${{env.ACCOUNT_ID}}:role/notification-terraform-plan
          role_session_name: NotifyTerraformPlan
      
      - name: Download TFVars
        run: |
          sudo mkdir -p aws && cd aws
          op read op://4eyyuwddp6w4vxlabrr2i2duxm/"TERRAFORM_SECRETS_${{env.ENVIRONMENT}}"/notesPlain > ${{env.ENVIRONMENT}}.tfvars
      
      - name: Terragrunt Init
        id: tf-init
        run: |
          cd env/${{env.ENVIRONMENT}}
          # Run init with ignore-dependency-errors to avoid trying to resolve outputs
          terragrunt run-all init --terragrunt-non-interactive --terragrunt-ignore-dependency-errors
      
      - name: Terraform Format Check (Terraform files only)
        id: tf-format
        run: |
          cd env/${{env.ENVIRONMENT}}
          # Use find to format only .tf files, not .hcl files
          find . -name "*.tf" -not -path "*/.terragrunt-cache/*" -exec terraform fmt -check -diff {} +
      
      - name: Terragrunt Format Check (Terragrunt HCL files)
        id: tg-format
        run: |
          cd env/${{env.ENVIRONMENT}}
          terragrunt hclfmt --check

      - name: Terragrunt Validate
        id: tf-validate
        run: |
          cd env/${{env.ENVIRONMENT}}
          # Use ignore-dependency-errors since we're only validating syntax, not checking actual state
          terragrunt run-all validate --terragrunt-non-interactive --terragrunt-ignore-dependency-errors
