name: "Delete Dev Environment"

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

env:
  AWS_REGION: ca-central-1
  OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  
  terragrunt-destroy-common:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - uses: ./.github/actions/setup-terraform
        with:
          role_to_assume: arn:aws:iam::800095993820:role/notification-terraform-apply
          role_session_name: NotifyTerraformDestroy

      - name: terragrunt destroy common
        run: |
          cd env/dev/common
          terragrunt destroy --terragrunt-non-interactive -auto-approve

  terragrunt-destroy-ecr:
    if: |
      always() &&
      !contains(needs.*.result, 'failure') &&
      !contains(needs.*.result, 'cancelled')
    runs-on: ubuntu-latest  
    
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        
      - name: setup-terraform
        uses: ./.github/actions/setup-terraform
        with:
          role_to_assume: arn:aws:iam::800095993820:role/notification-terraform-apply
          role_session_name: NotifyTerraformDestroy        

      - name: terragrunt destroy ECR
        run: |
          cd env/dev/ecr
          terragrunt destroy --terragrunt-non-interactive -auto-approve

  terragrunt-destroy-ses_receiving_emails:
    if: |
      always() &&
      !contains(needs.*.result, 'failure') &&
      !contains(needs.*.result, 'cancelled')
    runs-on: ubuntu-latest  
    needs: [terragrunt-destroy-common,terragrunt-destroy-ecr]

    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        
      - name: setup-terraform
        uses: ./.github/actions/setup-terraform
        with:
          role_to_assume: arn:aws:iam::800095993820:role/notification-terraform-apply
          role_session_name: NotifyTerraformDestroy        

      - name: terragrunt destroy ses_receiving_emails
        run: |
          cd env/dev/ses_receiving_emails
          terragrunt destroy --terragrunt-non-interactive -auto-approve

  terragrunt-destroy-dns:
    if: |
      always() &&
      !contains(needs.*.result, 'failure') &&
      !contains(needs.*.result, 'cancelled')
    runs-on: ubuntu-latest  
    needs: [terragrunt-destroy-common,terragrunt-destroy-ses_receiving_emails]

    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: setup-terraform
        uses: ./.github/actions/setup-terraform
        with:
          role_to_assume: arn:aws:iam::800095993820:role/notification-terraform-apply
          role_session_name: NotifyTerraformDestroy            

      - name: terragrunt destroy dns
        run: |
          cd env/dev/dns
          terragrunt destroy --terragrunt-non-interactive -auto-approve

  terragrunt-destroy-ses_validation_dns_entries:
    if: |
      always() &&
      !contains(needs.*.result, 'failure') &&
      !contains(needs.*.result, 'cancelled')
    runs-on: ubuntu-latest  
    needs: [terragrunt-destroy-common,terragrunt-destroy-dns]

    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        
      - name: setup-terraform
        uses: ./.github/actions/setup-terraform
        with:
          role_to_assume: arn:aws:iam::800095993820:role/notification-terraform-apply
          role_session_name: NotifyTerraformDestroy        

      - name: terragrunt destroy ses_validation_dns_entries
        run: |
          cd env/dev/ses_validation_dns_entries
          terragrunt destroy --terragrunt-non-interactive -auto-approve


  terragrunt-destroy-cloudfront:
    if: |
      always() &&
      !contains(needs.*.result, 'failure') &&
      !contains(needs.*.result, 'cancelled')
    runs-on: ubuntu-latest  
    needs: [terragrunt-destroy-common]

    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        
      - name: setup-terraform
        uses: ./.github/actions/setup-terraform
        with:
          role_to_assume: arn:aws:iam::800095993820:role/notification-terraform-apply
          role_session_name: NotifyTerraformDestroy        

      - name: terragrunt destroy cloudfront
        run: |
          cd env/dev/cloudfront
          terragrunt destroy --terragrunt-non-interactive -auto-approve 

  terragrunt-destroy-eks:
    if: |
      always() &&
      !contains(needs.*.result, 'failure') &&
      !contains(needs.*.result, 'cancelled')
    runs-on: ubuntu-latest  
    needs: [terragrunt-destroy-common,terragrunt-destroy-dns,terragrunt-destroy-cloudfront]

    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        
      - name: setup-terraform
        uses: ./.github/actions/setup-terraform
        with:
          role_to_assume: arn:aws:iam::800095993820:role/notification-terraform-apply
          role_session_name: NotifyTerraformDestroy           

      - name: terragrunt destroy eks
        run: |
          cd env/dev/eks
          terragrunt destroy --terragrunt-non-interactive -auto-approve

  terragrunt-destroy-elasticache:
    if: |
      always() &&
      !contains(needs.*.result, 'failure') &&
      !contains(needs.*.result, 'cancelled')
    runs-on: ubuntu-latest  
    needs: [terragrunt-destroy-common,terragrunt-destroy-eks]

    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        
      - name: setup-terraform
        uses: ./.github/actions/setup-terraform
        with:
          role_to_assume: arn:aws:iam::800095993820:role/notification-terraform-apply
          role_session_name: NotifyTerraformDestroy        

      - name: terragrunt destroy elasticache
        run: |
          cd env/dev/elasticache
          terragrunt destroy --terragrunt-non-interactive -auto-approve

  terragrunt-destroy-rds:
    if: |
      always() &&
      !contains(needs.*.result, 'failure') &&
      !contains(needs.*.result, 'cancelled')
    runs-on: ubuntu-latest  
    needs: [terragrunt-destroy-common,terragrunt-destroy-eks]

    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        
      - name: setup-terraform
        uses: ./.github/actions/setup-terraform
        with:
          role_to_assume: arn:aws:iam::800095993820:role/notification-terraform-apply
          role_session_name: NotifyTerraformDestroy        

      - name: terragrunt destroy rds
        run: |
          cd env/dev/rds
          terragrunt destroy --terragrunt-non-interactive -auto-approve

  terragrunt-destroy-lambda-api:
    if: |
      always() &&
      !contains(needs.*.result, 'failure') &&
      !contains(needs.*.result, 'cancelled')
    runs-on: ubuntu-latest  
    needs: [terragrunt-destroy-common,terragrunt-destroy-eks,terragrunt-destroy-ecr,terragrunt-destroy-rds]

    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        
      - name: setup-terraform
        uses: ./.github/actions/setup-terraform
        with:
          role_to_assume: arn:aws:iam::800095993820:role/notification-terraform-apply
          role_session_name: NotifyTerraformDestroy        

      - name: terragrunt destroy lambda-api
        run: |
          cd env/dev/lambda-api
          terragrunt destroy --terragrunt-non-interactive -auto-approve

  terragrunt-destroy-lambda-admin-pr:
    if: |
      always() &&
      !contains(needs.*.result, 'failure') &&
      !contains(needs.*.result, 'cancelled')
    runs-on: ubuntu-latest  
    needs: [terragrunt-destroy-common,terragrunt-destroy-elasticache,terragrunt-destroy-ecr]

    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        
      - name: setup-terraform
        uses: ./.github/actions/setup-terraform
        with:
          role_to_assume: arn:aws:iam::800095993820:role/notification-terraform-apply
          role_session_name: NotifyTerraformDestroy        

      - name: terragrunt destroy lambda-admin-pr
        run: |
          cd env/dev/lambda-admin-pr
          terragrunt destroy --terragrunt-non-interactive -auto-approve

  terragrunt-destroy-performance-test:
    if: |
      always() &&
      !contains(needs.*.result, 'failure') &&
      !contains(needs.*.result, 'cancelled')
    runs-on: ubuntu-latest  
    needs: [terragrunt-destroy-common,terragrunt-destroy-eks,terragrunt-destroy-ecr]

    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        
      - name: setup-terraform
        uses: ./.github/actions/setup-terraform
        with:
          role_to_assume: arn:aws:iam::800095993820:role/notification-terraform-apply
          role_session_name: NotifyTerraformDestroy           

      - name: terragrunt destroy performance-test
        run: |
          cd env/dev/performance-test
          terragrunt destroy --terragrunt-non-interactive -auto-approve

  terragrunt-destroy-heartbeat:
    if: |
      always() &&
      !contains(needs.*.result, 'failure') &&
      !contains(needs.*.result, 'cancelled')
    runs-on: ubuntu-latest  
    needs: [terragrunt-destroy-common,terragrunt-destroy-ecr]

    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        
      - name: setup-terraform
        uses: ./.github/actions/setup-terraform
        with:
          role_to_assume: arn:aws:iam::800095993820:role/notification-terraform-apply
          role_session_name: NotifyTerraformDestroy        

      - name: terragrunt destroy heartbeat
        run: |
          cd env/dev/heartbeat
          terragrunt destroy --terragrunt-non-interactive -auto-approve

  terragrunt-destroy-database-tools:
    if: |
      always() &&
      !contains(needs.*.result, 'failure') &&
      !contains(needs.*.result, 'cancelled')
    runs-on: ubuntu-latest  
    needs: [terragrunt-destroy-common,terragrunt-destroy-eks,terragrunt-destroy-rds]

    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        
      - name: setup-terraform
        uses: ./.github/actions/setup-terraform
        with:
          role_to_assume: arn:aws:iam::800095993820:role/notification-terraform-apply
          role_session_name: NotifyTerraformDestroy          

      - name: terragrunt destroy database-tools
        run: |
          cd env/dev/database-tools
          terragrunt destroy --terragrunt-non-interactive -auto-approve

  terragrunt-destroy-quicksight:
    if: |
      always() &&
      !contains(needs.*.result, 'failure') &&
      !contains(needs.*.result, 'cancelled')
    runs-on: ubuntu-latest  
    needs: [terragrunt-destroy-common,terragrunt-destroy-eks,terragrunt-destroy-rds]

    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        
      - name: setup-terraform
        uses: ./.github/actions/setup-terraform
        with:
          role_to_assume: arn:aws:iam::800095993820:role/notification-terraform-apply
          role_session_name: NotifyTerraformDestroy                  

      - name: terragrunt destroy quicksight
        run: |
          cd env/dev/quicksight
          terragrunt destroy --terragrunt-non-interactive -auto-approve

  terragrunt-destroy-lambda-google-cidr:
    if: |
      always() &&
      !contains(needs.*.result, 'failure') &&
      !contains(needs.*.result, 'cancelled')
    runs-on: ubuntu-latest  
    needs: [terragrunt-destroy-common,terragrunt-destroy-eks,terragrunt-destroy-ecr]

    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        
      - name: setup-terraform
        uses: ./.github/actions/setup-terraform
        with:
          role_to_assume: arn:aws:iam::800095993820:role/notification-terraform-apply
          role_session_name: NotifyTerraformDestroy        

      - name: terragrunt destroy lambda-google-cidr
        run: |
          cd env/dev/lambda-google-cidr
          terragrunt destroy --terragrunt-non-interactive -auto-approve

  terragrunt-destroy-ses_to_sqs_email_callbacks:
    if: |
      always() &&
      !contains(needs.*.result, 'failure') &&
      !contains(needs.*.result, 'cancelled')
    runs-on: ubuntu-latest  
    needs: [terragrunt-destroy-common,terragrunt-destroy-ecr]

    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        
      - name: setup-terraform
        uses: ./.github/actions/setup-terraform
        with:
          role_to_assume: arn:aws:iam::800095993820:role/notification-terraform-apply
          role_session_name: NotifyTerraformDestroy        

      - name: terragrunt destroy ses_to_sqs_email_callbacks
        run: |
          cd env/dev/ses_to_sqs_email_callbacks
          terragrunt destroy --terragrunt-non-interactive -auto-approve

  terragrunt-destroy-sns_to_sqs_sms_callbacks:
    if: |
      always() &&
      !contains(needs.*.result, 'failure') &&
      !contains(needs.*.result, 'cancelled')
    runs-on: ubuntu-latest  
    needs: [terragrunt-destroy-common,terragrunt-destroy-ecr]

    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        
      - name: setup-terraform
        uses: ./.github/actions/setup-terraform
        with:
          role_to_assume: arn:aws:iam::800095993820:role/notification-terraform-apply
          role_session_name: NotifyTerraformDestroy        

      - name: terragrunt destroy sns_to_sqs_sms_callbacks
        run: |
          cd env/dev/sns_to_sqs_sms_callbacks
          terragrunt destroy --terragrunt-non-interactive -auto-approve

  terragrunt-destroy-pinpoint_to_sqs_sms_callbacks:
    if: |
      always() &&
      !contains(needs.*.result, 'failure') &&
      !contains(needs.*.result, 'cancelled')
    runs-on: ubuntu-latest  
    needs: [terragrunt-destroy-common,terragrunt-destroy-ecr]

    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        
      - name: setup-terraform
        uses: ./.github/actions/setup-terraform
        with:
          role_to_assume: arn:aws:iam::800095993820:role/notification-terraform-apply
          role_session_name: NotifyTerraformDestroy        

      - name: terragrunt destroy pinpoint_to_sqs_sms_callbacks
        run: |
          cd env/dev/pinpoint_to_sqs_sms_callbacks
          terragrunt destroy --terragrunt-non-interactive -auto-approve

  terragrunt-destroy-system_status:
    if: |
      always() &&
      !contains(needs.*.result, 'failure') &&
      !contains(needs.*.result, 'cancelled')
    runs-on: ubuntu-latest  
    needs: [terragrunt-destroy-common,terragrunt-destroy-ecr,terragrunt-destroy-rds,terragrunt-destroy-eks]

    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        
      - name: setup-terraform
        uses: ./.github/actions/setup-terraform
        with:
          role_to_assume: arn:aws:iam::800095993820:role/notification-terraform-apply
          role_session_name: NotifyTerraformDestroy        

      - name: terragrunt destroy system_status
        run: |
          cd env/dev/system_status
          terragrunt destroy --terragrunt-non-interactive -auto-approve

  terragrunt-destroy-system_status_static_site:
    if: |
      always() &&
      !contains(needs.*.result, 'failure') &&
      !contains(needs.*.result, 'cancelled')
    needs: [terragrunt-destroy-common,terragrunt-destroy-system_status]
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        
      - name: setup-terraform
        uses: ./.github/actions/setup-terraform
        with:
          role_to_assume: arn:aws:iam::800095993820:role/notification-terraform-apply
          role_session_name: NotifyTerraformDestroy         

      - name: terragrunt destroy aws/system_status_static_site
        run: |
          cd env/dev/system_status_static_site
          terragrunt destroy --terragrunt-non-interactive -auto-approve

  terragrunt-destroy-newrelic:
    if: |
      always() &&
      !contains(needs.*.result, 'failure') &&
      !contains(needs.*.result, 'cancelled')
    needs: [terragrunt-destroy-common]
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        
      - name: setup-terraform
        uses: ./.github/actions/setup-terraform
        with:
          role_to_assume: arn:aws:iam::800095993820:role/notification-terraform-apply
          role_session_name: NotifyTerraformDestroy        

      - name: terragrunt destroy aws/newrelic
        run: |
          cd env/dev/newrelic
          terragrunt destroy --terragrunt-non-interactive -auto-approve

  bump-version-and-push-tag:
    if: |
        always() &&
        github.event_name != 'workflow_dispatch' &&
        !contains(needs.*.result, 'failure') &&
        !contains(needs.*.result, 'cancelled')
    runs-on: ubuntu-latest
    needs: [terragrunt-destroy-common,terragrunt-destroy-ecr,terragrunt-destroy-dns,terragrunt-destroy-ses_validation_dns_entries,terragrunt-destroy-cloudfront,terragrunt-destroy-eks,terragrunt-destroy-elasticache,terragrunt-destroy-rds,terragrunt-destroy-lambda-api,terragrunt-destroy-lambda-admin-pr,terragrunt-destroy-performance-test,terragrunt-destroy-heartbeat,terragrunt-destroy-database-tools,terragrunt-destroy-quicksight,terragrunt-destroy-lambda-google-cidr,terragrunt-destroy-ses_to_sqs_email_callbacks,terragrunt-destroy-sns_to_sqs_sms_callbacks,terragrunt-destroy-pinpoint_to_sqs_sms_callbacks,terragrunt-destroy-system_status,terragrunt-destroy-ses_receiving_emails,terragrunt-destroy-system_status_static_site,terragrunt-destroy-newrelic]
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        
      - name: bump-version-and-push-tag
        uses: mathieudutour/github-tag-action@bcb832838e1612ff92089d914bccc0fd39458223 # v4.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: main          