name: "Terragrunt Format and Validate - Staging"

env:
  ENVIRONMENT: staging
  ACCOUNT_ID: ${{ secrets.STAGING_AWS_ACCOUNT_ID }}
  AWS_REGION: ca-central-1
  OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN_STAGING }}
  WORKFLOW: true
  TF_PLUGIN_CACHE_DIR: /tmp/.terraform.d/plugin-cache

on:
  workflow_dispatch:
  pull_request:
    paths:
      - ".env"
      - "aws/**"
      - "env/$ENVIRONMENT/**"
      - "env/terragrunt.hcl"
      - "env/*.tfvars"
      - ".github/workflows/terragrunt_plan_$ENVIRONMENT.yml"

permissions:
  id-token: write # This is required for requesting the OIDC JWT
  contents: write # This is required for actions/checkout
  pull-requests: write

jobs:
  terragrunt-format:
    name: Terragrunt Fmt & Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      - name: Free Disk Space
        run: |
          echo "Disk space before cleanup:"
          df -h
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/share/boost
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          echo "Disk space after cleanup:"
          df -h

      - name: Setup Terraform
        uses: ./.github/actions/setup-terraform
        with:
          role_to_assume: arn:aws:iam::${{env.ACCOUNT_ID}}:role/notification-terraform-plan
          role_session_name: NotifyTerraformPlan
      
      - name: Cache Terraform providers
        uses: actions/cache@v4
        with:
          path: /tmp/.terraform.d/plugin-cache
          key: terraform-providers-${{ hashFiles('env/terragrunt.hcl', 'aws/**/.terraform.lock.hcl') }}
          restore-keys: |
            terraform-providers-

      - name: Cache Terragrunt cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.terragrunt-cache
            .terragrunt-cache
          key: terragrunt-cache-${{ github.sha }}
          restore-keys: |
            terragrunt-cache-
      
      - name: Download TFVars
        run: |
          sudo mkdir -p aws && cd aws
          op read op://4eyyuwddp6w4vxlabrr2i2duxm/"TERRAFORM_SECRETS_${{env.ENVIRONMENT}}"/notesPlain > ${{env.ENVIRONMENT}}.tfvars
      
      - name: Terragrunt Init
        id: tf-init
        run: |
          cd env/${{env.ENVIRONMENT}}
          terragrunt run-all init --terragrunt-non-interactive
      
      - name: Terragrunt Format
        id: tf-format
        run: |
          cd env/${{env.ENVIRONMENT}}
          terragrunt run-all fmt --check

      - name: Terragrunt Validate
        id: tf-validate
        run: |
          cd env/${{env.ENVIRONMENT}}
          terragrunt run-all validate --terragrunt-non-interactive
